# Generated by Django 5.2 on 2025-07-27 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Karma', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productStockName', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='productStockID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Karma.productstock'),
        ),
    ]
