# Generated by Django 5.2 on 2025-07-29 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Karma', '0002_productstock_product_productstockid'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
