# Generated by Django 5.2 on 2025-08-03 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Karma', '0003_accesstoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brandName', models.CharField(max_length=200, null=True)),
                ('brandImage', models.ImageField(blank=True, null=True, upload_to='images/Brands/')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='brandid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Karma.brand'),
        ),
    ]
