# Generated by Django 5.2 on 2025-08-03 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Karma', '0004_brand_category_brandid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='brandid',
        ),
        migrations.AddField(
            model_name='product',
            name='brandid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Karma.brand'),
        ),
    ]
