# Generated by Django 5.2 on 2025-08-05 02:24

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Karma', '0005_remove_category_brandid_product_brandid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogName', models.CharField(max_length=200, null=True)),
                ('blogDescript', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('blogImage', models.ImageField(blank=True, null=True, upload_to='images/Blogs/')),
                ('blogDate', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlogDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogDetailName', models.CharField(max_length=200, null=True)),
                ('Description', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('Information', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('Reviews', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('blogDetailDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('blogID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Karma.blog')),
            ],
        ),
        migrations.CreateModel(
            name='BlogDetailImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogDetailImageName', models.CharField(max_length=200, null=True)),
                ('blogDetailImage', models.ImageField(blank=True, null=True, upload_to='images/BlogDetail/')),
                ('imageDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('blogID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Karma.blog')),
            ],
        ),
    ]
