# Generated by Django 5.2 on 2025-08-05 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Karma', '0006_blog_blogdetail_blogdetailimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogCategoryName', models.CharField(max_length=200, null=True)),
                ('blogCategoryImage', models.ImageField(blank=True, null=True, upload_to='images/BlogCategories/')),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='blogCategoryID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Karma.blogcategory'),
        ),
    ]
